excluidos = [
'Favorites',
'Otros sitios',
'Más Deportes',
'Redes sociales',
'Ediciones',
'COPA LIBERTADORES',
'MERCADO DE PASES',
'BARCELONA',
'NOTICIAS DESTACADAS',
'La agenda del fútbol argentino',
'Cómo acceder a ESPN Play',
'ESPN App: lo mejor del deporte al alcance de la mano',
'Programación de ESPN',
]
